not_sf_template:
- РТ?НАЯ НАК[Л|П]А[Д|П]
- ФОРМА № ТОРГ
- ОТЧЕТ

inn_kpp_num_template: (\d{10}).*?(\d{9})

trash_template: ^[\(|{][А-Я0-9]*[\)|}]?$

# Приложение № 1 к постановлению Правительства Российской Федерации 
# 'Исправление №',
trash_word_template:
- РИЛОЖЕ
- ОСТАНО
- АВИТЕ
- ССИЙ
- ЕДЕРА
- "—"
- "="
- АВЛЕНИЕ


replace_template:
- ' 0Г'
- ' 0Т'
- ' ОТ'
- ' ЭТ'
- ' АТ'
- ' ОГ'
- ' ЕТ'

sf_num_template:
- "[Ф|Р]АКТУ[Р|Г]А ?[№|М]?"
- ФА КТУРА ?[№|М]?
- ФА РА[№|М]?
- Ф ТУРА ?[№|М]?
- ФАКТ?УРА ?[№|М]?
- ФАКТУОА ?[№|М]?


# sf_num_template:
# - СЧЁТ-ФАКТУРА ?[№|М]?
# - СЧЕТ[- ]ФА КТУРА ?[№|М]?
# - СЧЕТ - ФАКТУРА ?[№|М]?
# - СЧЕТЕ ФАКТУРА ?[№|М]?
# - СЧЕТФАКТУРА ?[№|М]?
# - СЧЕТ -ФАКТУРА ?[№|М]?
# - СЧЕТ[-\.]ФАКТУРА ?[№|М]?
# - СЧЕТ-ФА РА[№|М]?
# - СЧЕТ\.? ФАКТУРА ?[№|М]?
# - СЧЕТАРАКТУРА ?[№|М]?
# - С Т Ф ТУРА ?[№|М]?
# - СЧЕТ-=ФАКТУРА ?[№|М]?
# - СЧЕТ ?ФАКТ?УРА ?[№|М]?
# - БЕ ФАКТУОА ?[№|М]?
# - С?[Ч|#][Ё|Е]Т-[Ф|Р]АКТУ[Р|Г]А ?[№|М]?



inn_kpp_template:
- ИНИЖПП
- ИНН/КПИ
- ИНН/КПН
- ИНН/КПП
- ИНН / КПП
- ИННАХПИ
- ИННЖАЙ
- ИННЖАП
- ИННЖИП
- ИННЖКЛПП
- ИННЖКПП
- ИННЖПИ
- ИННЖПЛ
- ИННЖПП
- ИННИЖКПП
- ИННИЖПЛ
- ИННИЖПП
- ИННИКПЛ
- ИННИКПП
- ИННИЛЯ
- ИННИПП
- ИННИХПП
- ИННИЮПП
- ИННКПИ
- ИННКПЛ
- ИННКПП
- ИННУКПП
- ИННЫКПП
- ИНЫЖКЛПП
- ННИКПП
- ИННИКПГ
- ИНН/ИКАП
- ИННЖГП
- ИННЖПЮ
- ИННЛКПИ)
- ИННЛОПИ
- ИННЖПО
- ИНН/КПТ


seller_template: ПРОДАВ[Ц|И|Н]А:?
buyer_template: ПОКУ[П|Л]АТЕЛЯ:?

bill_template: СЧЕТ|СЧЁТ

month:
  ЯНВАРЯ: '01'
  ФЕВРАЛЯ: '02'
  ФЕВРАПЯ: '02'
  МАРТА: '03'
  МЕРТА: '03'
  АПРЕЛЯ: '04'
  МАЯ: '05'
  ИЮНЯ: '06'
  ИЮЛЯ: '07'
  АВГУСТА: '08'
  ЗАГУСТА: '08'
  ЗАТУСТА: '08'
  СЕНТЯБРЯ: '09'
  ОКТЯБРЯ: '10'
  НОЯБРЯ: '11'
  ДЕКАБРЯ: '12'

nums_letter_correct:
    О: 0
    З: 3
    В: 8
    Э: 9
