tn_template:
- ТРАНСПОРТНАЯ НАКЛАДНАЯ
- ТОВАРНАЯ НАК[Л|П]А[Д|П]НАЯ

replace_template:
- ' 0Г'
- ' 0Т'
- ' ОТ'
- ' ЭТ'

sf_num_template:
- СЧЁТ-ФАКТУРА [№|М]?
- СЧЕТ[- ]ФА КТУРА [№|М]?
- СЧЕТ - ФАКТУРА [№|М]?
- СЧЕТЕ ФАКТУРА [№|М]?
- СЧЕТФАКТУРА [№|М]?
- СЧЕТ -ФАКТУРА [№|М]?
- СЧЕТ[-\.]ФАКТУРА [№|М]?
- СЧЕТ-ФА РА[№|М]?
- СЧЕТ ФАКТУРА [№|М]?
- СЧЕТАРАКТУРА [№|М]?
- С Т Ф ТУРА [№|М]?

inn_kpp_template:
- ИНИЖПП
- ИНН/КПИ
- ИНН/КПН
- ИНН/КПП
- ИННАХПИ
- ИННЖАЙ
- ИННЖАП
- ИННЖИП
- ИННЖКЛПП
- ИННЖКПП
- ИННЖПИ
- ИННЖПЛ
- ИННЖПП
- ИННИЖКПП
- ИННИЖПЛ
- ИННИЖПП
- ИННИКПЛ
- ИННИКПП
- ИННИЛЯ
- ИННИПП
- ИННИХПП
- ИННИЮПП
- ИННКПИ
- ИННКПЛ
- ИННКПП
- ИННУКПП
- ИННЫКПП
- ИНЫЖКЛПП
- ННИКПП
- ИНН / КПП

seller_template: ПРОДАВЦА:?
buyer_template: ПОКУ[П|Л]АТЕЛЯ:?

month:
  ЯНВАРЯ: '01'
  ФЕВРАЛЯ: '02'
  ФЕВРАПЯ: '02'
  МАРТА: '03'
  АПРЕЛЯ: '04'
  МАЯ: '05'
  ИЮНЯ: '06'
  ИЮЛЯ: '07'
  АВГУСТА: '08'
  ЗАГУСТА: '08'
  СЕНТЯБРЯ: '09'
  ОКТЯБРЯ: '10'
  НОЯБРЯ: '11'
  ДЕКАБРЯ: '12'

nums_letter_correct:
    З: 3
    В: 8
    Э: 9
